# Generated by Django 3.1.5 on 2021-02-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
    ]
